#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Start manager directly or as a daemon.
"""

import manager
from daemon import Daemon
import sys


class KHomeDaemon(Daemon):
    """ Daemon starting KHome server as daemon in Linux OS. """
    def run(self):
        return manager.start()

    def status(self):
        if self.get_pid():
            print("%s is running!" % self.name)
        else:
            print("%s is sleeping." % self.name)


if __name__ == "__main__":
    if len(sys.argv) == 2:
        daemon = KHomeDaemon('/var/run/KHome.pid', 'KHome server')
        command = sys.argv[1]
        if command == 'start':
            daemon.start()
        elif command == 'stop':
            daemon.stop()
        elif command == 'restart':
            daemon.restart()
        elif command == 'status':
            daemon.status()
        else:
            print('Unknown command "%s". Please use the following: {start|stop|restart|status}' % command)
            sys.exit(2)

        sys.exit(0)
    else:
        # manager.start('192.168.0.13')
        manager.start('192.168.10.200')
